server:
  port: 8282
  ssl:
    key-alias: medrem-ssl
    key-store-type: JKS
    key-store-password: Romio@1993
    key-store-provider: SUN
    key-store: classpath:certificate/medrem-ssl.jks
    
  error:
    include-stacktrace: never
spring:
  data:
    mongodb:
      auto-index-creation: true
      
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true