server:
  port: 8761
  error:
    include-stacktrace: never

spring:
  data:
    mongodb:
      auto-index-creation: true
security:
  require-ssl: true
  ssl:
    key-store-password: Romio@1993
    key-store: src/main/resources/certificate/medrem-ssl.p12
    key-store-type: PKCS12

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

